$("#dom").text("Dom");
$("#moduły").text("Moduły");
$("#ustawienia").text("Ustawienia");
$("#reguły").text("Zasady");
$("#więcej").text("Duże");
$("#integracja").text("Integracja");
$("#currentmonitor").text("diyBMS - aktualny bocznik");
$("#storage").text("Pamięć");
$("#avrprogrammer").text("Programator AVR");
$("#o").text("Informacje");
$("#modulesPage > h1").text("Moduły strony");
$("#globalConfig > h2").text("Ogólna konfiguracja");
$("#globalConfig > p").text("Konfiguracja modułu");
$("#mpBank").text("Komórka");
$("#mpModule").text("Moduł");
$("#mpVoltage").text("Napięcie");
$("#mpvmin").text("V. minimum");
$("#mptint").text("Temperatura temperatury °C");
$("#mptext").text("Czujnik temperatury ogrzewania °C");
$("#mpbypass").text("Bajpas %");
$("#mpbpc").text("Uszkodzone pakiety");
$("#mppktr").text("Otrzymane paczki");
$("#mpbal").text("Balansowanie (mAh)");
$("#error1").text("Kontroler ma problemy z komunikacją z modułem.");
$("#error3").text("Kontroler jest skonfigurowany z dostawcami modułami.");
$("#error4").text("Oczekiwanie na odpowiedź modułu.");
$("#error5").text("Moduł zarejestrowany 0 woltów, sprawdź odpowiedni.");
$("#error6").text("Nie ma wystarczającej ilości miejsca w pamięci kontrolera.");
$("#error7").text("Zatrzymanie jazdy");
$("#iperror").text("Nie można zweryfikować się z kontrolerem w celu aktualizacji postępu.");
$("#jslibrary").text("Biblioteka JavaScript nie została załadowana prawidłowo, odśwież stronę.");
$("#saveerror").text("Ustawienia nie zostały wprowadzone.");
$("#savesuccess").text("Zapisane ustawienia");
$("#warning1").text("Uwaga: zasilanie obejścia moduł różni się od ustawień globalnego");
$("#warning2").text("Uwaga: temperatura obejścia modułu różni się od ustawień globalnego");
$("#warning3").text("Ostrzeżenie: moduły mają różne wersje oprogramowania, co może spowodować niestabilność");
$("#warning4").text("Ostrzeżenie: moduły mają różne wersje sprzętowe");
$("#warning5").text("Ostrzeżenie: logowanie jest włączone, karta SD nie została znaleziona");
$("#warning6").text("Ostrzeżenie: niektóre funkcje są obsługiwane w trakcie programowania AVR");
$("label[for='NTPServer']").text("Serwer NTP");
$("label[for='NTPZoneHour']").text("Strefa czasowa (ZEGAR)");
$("#rt1").text("DIYBMS obsługujący przekaźniki do prawidłowej obsługi ładowarek, styczników i odbiorników. Zasady obsługi działają w twojej sytuacji");
$("#rt2").text("Reguły są oceniane od podłączenia do przewodu (od dołu do góry). Steruj przekaźnikiem za pomocą komunikacji. X oznacza ignorowanie wartości niższych wierszy");
$("#rt3").text("Reguły wzrostu się aktywne, gdy wartość przekraczająca wartość alarmową i dokładnie wzrasta się nieaktywne, gdy wartość poniżej wartości przywracania. Pozwala na dodanie niestabilnych funkcji.");
$("#rt4").text("Reguły 'Timer 1' i 'Timer 2' właściwie ustawiają czas, reguła staje się aktywna, gdy osiągnięta jest liczba minut po. Na przykład, timer 1 aktywuje wartość alarmu 495 i resetuje wartość 555 o 08:15 i wyłącza się o 21:15. Ta reguła działa tylko wtedy, gdy masz wsparcie z Internetem (NTP).");
$("#rt5").text("Czas po nocy w zjawisku:");
$("#rt6").text("Zatrzymanie działania jest aktywowane przez połączenie J1, po włączeniu należy zresetować sterownik");
$("#rf1").text("Reguła");
$("#rf2").text("Wartość alarmu");
$("#rf3").text("Zresetuj wartość");
$("#rf4").text("Stan przekaźnika");
$("label[for='rule1value']").text("Zatrzymanie jazdy");
//Wewnętrzny błąd BMS
$("label[for='rule1value']").text("Błąd wewnętrzny BMS");
//Przepięcie pojedynczego ogniwa (mV)
$("label[for='rule3value']").text("Przepięcie pojedynczego ogniwa (mV)");
//Ogniwo pod napięciem (mV)
$("label[for='rule4value']").text("Nie doładowanie ogniwa (mV)");
// Nadmierna temperatura modułu (wewnętrzna) °C
$("label[for='rule5value']").text("Maksymalna temperatura modułu (wewnętrzna) °C");
//Moduł za niski (wewnętrzny)
$("label[for='rule6value']").text("Minimalna temperatura modułu (wewnętrzna)");
//Przegrzanie ogniwa (zewnętrzne)
$("label[for='rule7value']").text("Maksymalna temperatura ogniwa (na zewnątrz)");
// Ogniwo za niskie (zewnętrzne)
$("label[for='rule8value']").text("Minimalna temperatura ogniwa (na zewnątrz)");
//Przepięcie banku (mV)
$("label[for='rule9value']").text("Maksymalne obciążenie baterii (mV)");
//Bank pod napięciem (mV)
$("label[for='rule10value']").text("Minimalne napięcie efektu (mV)");
//Przepięcie banku (mV)
//Bank pod napięciem (mV)
//Zakres banku/odchylenie (mV)
//Zegar 2
$("etykieta[for='reguła14wartość']").text("Zegar 2");
//Zegar 1
$("etykieta[dla='reguła15wartość']").text("Zegar 1");
$("etykieta[for='wartość domyślna']").text("Przekaźnik domyślny");
$("label[for='relaytype']").text("Typ przekaźnika");
$("label[for='g1']").text("Maksymalna temperatura Bajpasu");
$("label[for='g2']").text("Ograniczenie Bajpasu mV");
$("#sent > span.xt").text("Pakiet działający:");
$("#odebrano > span.xt").text("Otrzymane paczki:");
$("#roundtrip > span.xt").text("Tam iz powrotem (ms):");
$("#uptime > span.xt").text("Godziny pracy");
$("#qlen > span.xt").text("Długość wysyłania Q:");
$("#ip1").text("Integracja");
$("#ip2").text("Hasła musi być regularnie dla aktywowanych lub zmienionych usług.");
$("#ip3").text("Poradnik dotyczący instrukcji należy zrestartować sterownik");
$("#ip4").text("URI powinien działać jak mqtt://192.168.0.26:1833");
$("label[for='mqttEnabled']").text("Włącz");
$("etykieta[for='mqttTopic']").text("Temat");
$("etykieta[dla='mqttUri']").text("URI");
$("etykieta[dla='mqttPort']").text("Port");
$("label[for='mqttUsername']").text("Zaloguj się");
$("label[for='mqttPassword']").text("HASŁO");
$("#in2").text("API wersja 2.X");
$("#ap4").text("Pamiętaj, że jest to darmowy produkt do użytku osobistego. Aby pomóc w rozwoju projektu, zawsze możesz skorzystać z pomocy dobrego linku Patreon, a nawet bardzo dużo wnieść do dobrej drogi. Dziękuję!");
$("#ap5").text("Ostrzeżenie");
$("#ap6").text("To jest produkt/urządzenie domowe roboty, nie używaj go w środowisku o krytycznym zagrożeniu dla bezpieczeństwa lub w sytuacji, w której może chronić życie.");
$("#ap7").text("Nie udziela się żadnych gwarancji - Urządzenie może nie obsługiwać oczekiwań lub w ogóle nie działać.");
$("#ap8").text("Korzystanie z tego projektu odbywa się wyłącznie na własne ryzyko. Może się stać z porażeniem prądem elektrycznym, które może spowodować śmierć — w razie wątpliwości poszukaj pomocy.");
$("#ap8a").text("Korzystanie z tego projektu może być niezgodne z przepisami - w razie wątpliwości zakresu profesjonalnej porady.");
$("#mb1").text("Moduły i banki");
$("#mb2").text("DIYBMS obsługujący łącznie do 100 połączeń. Moduły te mogą wyglądać na różne banki w celu połączenia równoległego");
$("#mb3").text("Przykład: skonfigurowałeś 16 ogniw, 8 szeregowo i 2 boczne (8S2P).");
$("#mb4").text("Tylko modułu sprzętowego w wersji 4.4 lub nowszej obsługi standardowej szybkości transmisji. W przypadku zmiany szybkości działania należy skonfigurować kontroler, a także sprawdzić, że wszystkie moduły znajdują się w prawidłowym oprogramowaniu układowym.");
$("#globalSettingsButton").text("Zapisz ustawienia");
$("#diybmsCurrentMonitorPage > h1").text("Sterowanie prądem i zasilaniem DiyBMS");
$("#diybmsCurrentMonitorPage > div:nth-child(2) > h2").text("Połączenie");
$("#b1").text("Ustaw obsługi MODBUS do bieżącego zarządzania, oprócz obsługi.");
$("#b14").text("Urządzenie PZEM-017 wykorzystuje 9600.8,Brak,2");
$("label[for='CurrentMonDev']").text("Urządzenie");
$("label[for='modbusAddress']").text("Adres Modbus");
$("#b2").text("Parametry konfiguracyjne dla urządzenia RS485. Komunikacja odbywa się w pierwszym półdupleksie.");
$("label[for='rs485baudrate']").text("Szybkość transmisji");
$("label[for='rs485databit']").text("Bity danych");
$("label[for='rs485parity']").text("Bity danych");
$("label[for='rs485stopbit']").text("Bity stopu");
$("#avrprogPage > h1").text("Programator AVR");
$("#aboutPage > h1").text("Informacje");
$("#moc > rozpiętość.xt").text("Moc");
$("#shuntv > span.xt").text("Zablokuj");
$("#bieżący > span.xt").text("Aktualny");
$("#zakres0 > span.xt").text("Różnica:0");
$("#b11").text("Pojemność ładowania i ładowania ładowania/prąd szczątkowy są używane do obliczania stanu układu terapeutycznego SOC.");
$("#error2").text("Znaleziono kontrolera");
$("#missingmodule1").text("moduły, ale skonfigurowane dla");
$("#brakującymoduł2").text(".");
$("#genericerror").text("Błąd kontrolera");
$("#genericwarning").text("Ostrzeżenie kontrolera");
$("#warning7").text("Strona internetowa niezsynchronizowana z kontrolerem, odśwież stronę (F5)");
$("#amphout > span.xt").text("Wyjście Ah:");
$("#amphin > span.xt").text("Wejście Ah:");
$("#oos > span.xt").text("Błędy OOS:");
$("#badcrc > span.xt").text("Błędy CRC:");
$("#ignorowane > span.xt").text("Zignorowane poza:");
$("#canfail > span.xt").text("Błędy CAN:");
$("#cansent > span.xt").text("Wysłano CAN:");
$("#canrecd > span.xt").text("Otrzymano CAN:");
$("#graphOptions > span.xt").text("Wykres:");
$("#settingConfig > h2").text("Ustawienia modułu");
$("#ustawieniaForm > div > button").text("Zapisz");
$("#ap1").text("Oprogramowanie układowe i analiza drukowana");
$("#ap2").text("Wideo");
$("#ap9").text("Licencja");
$("#b3").text("Upewnij się, że aktualne ustawienia bocznika odpowiadają specyfikacjom poszczególnych rezystorów bocznikujących.");
$("#b4").text("Monitor prądu DIYBMS używa skali 40,96mV, więc wzmocnienie bocznikowe przekracza tę tę, że będzie proporcjonalnie zmniejszać.");
$("#b15").text("PZEM-017 wykorzystuje boczniki 75mV, stan szybki i alarmy nie są idealne w tym zastosowaniu. Obsługiwane są tylko boczniki 50, 100, 200, 300A.");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(2) > label").text(Napięcie wyjściowe bocznika (mV)");
$("#RS485Form > div > button").text("Zapisz");
$("#diybmsCurrentMonitorForm1 > div > button").text("Zapisz");
$("#currentmonbasic > h2").text("Ustawienia podstawowe");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(3) > label").text("Pojemność wynagrodzenia (Ah)");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(4) > label").text("Pełne zasilanie ładowania");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(5) > label").text("Prąd szczątkowy (ampery)");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(6) > label").text("Wydajność ładowania %");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(7) > label").text("Dopuszczalne wartości?");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(8) > label").text("Ostatnia wiadomość (milisekundy)");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(9) > label").text("Licznik Watchdoga");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(10) > label").text("Temperatura rdzenia procesora");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(11) > label").text("Wartość prądu bocznika mV");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(12) > label").text("Aktualny rozmiar LSB");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(13) > label").text("Rezystancja bocznika");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(14) > label").text("Model podejrzenia");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(15) > label").text("Wersja oprogramowania");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(16) > label").text("Dane oprogramowania układowego");
$("#diybmsCurrentMonitorForm2 > div > div:n-dziecko(17) > label").text("Stan przekaźnika");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(18) > label").text("Temperatura powyżej limitu");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(19) > label").text("Prąd powyżej limitu");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(20) > label").text("Prąd poniżej limitu");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(21) > label").text("Napięcie powyżej limitu");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(22) > label").text("Napięcie poniżej limitu");
$("#diybmsCurrentMonitorForm2 > div > div:nth-child(23) > label").text("Przekroczenie limitu mocy");
$("#diybmsCurrentMonitorForm2 > div > button:n-dziecko(24)").text("Zapisz");
$("#currentmonrefresh").text("Aktualizacja");
$("#currentmonadvanced > h2").text("Ustawienia zaawansowane");
$("#victronForm1 > div > div:nth-child(1) > table > thead > tr > th:nth-child(1)").text("Kiedy?");
$("#victronForm1 > div > div:nth-child(1) > table > thead > tr > th:nth-child(2)").text("Limit zasilania ładowania (CVL)");
$("#victronForm1 > div > div:nth-child(1) > table > thead > tr > th:nth-child(3)").text("Ograniczenie prądu ładowania (CCL)");
$("#victronForm1 > div > div:nth-child(1) > table > thead > tr > th:nth-child(4)").text("Ograniczenie prądu rozładowania (DCL)");
$("#victronForm1 > div > div:nth-child(1) > table > tbody > tr:nth-child(1) > td:nth-child(1)").text("Domyślny");
$("#victronForm1 > div > div:nth-child(1) > table > tbody > tr:nth-child(2) > td:nth-child(1)").text("Równoważenie");
$("#victronForm1 > div > div:nth-child(1) > table > tbody > tr:nth-child(3) > td:nth-child(1)").text("Błąd");
$("#victronForm1 > div > div:nth-child(2) > label").text("Włączenie połączenia CANBUS BMS z urządzeniem Victron");
$("#victronForm1 > div > button").text("Zapisz");
$("#b5").text("Jeśli chcesz kontrolować przekaźnik na monitorze bocznikowym, ustaw parametry tutaj. Normalnie nie musisz kontrolować kalibracji.");
$("#b6").text("Ograniczenie prądu jest używane podczas rozładowywania efektu, wpływ prądu jest używany podczas ładowania, więc można używać różnych limitów prądu rozładowania/ładowania.");
$("#b7").text("Ograniczenie temperatury zależy od temperatury matrycy układu skalowanego, która może nie reagować na bocznika. Obsługiwany jest tylko dodatni współczynnik temperatury.");
$("#b8").text("Wyzwalacze przekaźnika określają, które metody są stosowane do zamykania przekaźnika.");
$("#diybmsCurrentMonitorForm3 > div > div:n-dziecko(1) > label").text("Kalibracja");
$("#diybmsCurrentMonitorForm3 > div > div:nth-child(2) > label").text("Ograniczenie temperatury");
$("#diybmsCurrentMonitorForm3 > div > div:nth-child(3) > label").text("Ograniczenie zbytu dostępu do mocy");
$("#diybmsCurrentMonitorForm3 > div > div:nth-child(4) > label").text("Ograniczenie przepięcia");
$("#diybmsCurrentMonitorForm3 > div > div:nth-child(5) > label").text("Obecny limit przekroczony");
$("#diybmsCurrentMonitorForm3 > div > div:nth-child(6) > label").text("Zredukowany limit mocy");
$("#diybmsCurrentMonitorForm3 > div > div:nth-child(7) > label").text("Przekroczono limit mocy");
$("#diybmsCurrentMonitorForm3 > div > div:nth-child(8) > label").text("Współczynnik temperaturowy ppm");
$("#diybmsCurrentMonitorForm3 > div > button").text("Zapisz");
$("#b10").text("Ustawienia przekaźnika do kontroli prądu i współczynnika temperatury");
$("#diybmsCurrentMonitorForm4 > div > div:nth-child(1) > label").text("Współczynnik temperaturowy miejsca");
$("#diybmsCurrentMonitorForm4 > div > div:nth-child(2) > label").text("Działanie przekaźnika: Temperatura");
$("#diybmsCurrentMonitorForm4 > div > div:nth-child(3) > label").text("Wyzwolenie przekaźnika: przetężenie");
$("#diybmsCurrentMonitorForm4 > div > div:nth-child(4) > label").text("Działanie przekaźnika: Niski prąd");
$("#diybmsCurrentMonitorForm4 > div > div:nth-child(5) > label").text("Działanie przekaźnika: Przepięcie");
$("#diybmsCurrentMonitorForm4 > div > div:nth-child(6) > label").text("Sterowanie przekaźnika: Niskie zasilanie");
$("#diybmsCurrentMonitorForm4 > div > div:nth-child(7) > label").text("Działanie przekaźnika: Zasilanie");
$("#diybmsCurrentMonitorForm4 > div > button").text("Zapisz");
$("label[for='CurrentMonEnabled']").text("Aktywuj");
$("label[for='shuntmaxcur']").text("Maksymalny prąd bocznikowy");
$("label[for='totalSeriesModules']").text("Liczba jednostek (na przykład 8S)");
$("label[for='totalBanks']").text("Liczba równoległych banków (np. 2P)");
$("label[for='baudrate']").text("Szybkość łącza");
$("label[for='interpacketgap']").text("Odstęp między pakietami (ms)");
$("label[for='NTPDST']").text("Czas letni");
$("label[for='NTPZoneMin']").text("Strefa czasowa (minuty)");
$("label[for='Język']").text("Język");
$("label[for='VoltageHigh']").text("Wykres skali oceny (wysoki)");
$("label[for='VoltageLow']").text("Wykres skali oceny (niski)");
$("label[for='ModuleId']").text("Identyfikator modułu");
$("label[for='Version']").text("Wersja modułu");
$("label[for='BypassOverTempShutdown']").text("Bocznik wzrostu temperatury");
$("label[for='BypassThresholdmV']").text("Prog bocznika, mV");
$("label[for='Calib']").text("Współczynnik kalibracji");
$("label[for='ActualVoltage']").text("Kalkulator - Aktualne zmierzone zasilanie");
$("#Oblicz Kalibrację").text("Oblicz");
$("label[for='ExtBCoef']").text("Współczynnik temperatury ogrzewania");
$("label[for='IntBCoef']").text("Współczynnik temperatury otoczenia");
$("label[for='LoadRes']").text("Odporność na opłatę");
$("label[for='mVPerADC']").text("odczyty mV do ADC");
$("#rulesPage > h1").text("Zasady");
$("#settingsPage > h1").text("Ustawienia");
$("#settingsPage > div:nth-child(3) > h2").text("Protokół czasu sieciowego");
$("#b9").text("Czas jest ustawiany przez NTP, jeśli twój kontroler nie jest połączony z Internetem. Reguły działają na czas, aby dołączyć. Nie koryguje to automatycznie czasu letniego.");
$("#banksForm > div > button").text("Zapisz");
$("#ntpForm > div > button").text("Zapisz");
$("#settingsPage > div:nth-child(4) > h2").text("Wyświetl");
$("#displaySettingForm > div > button").text("Zapisz");
$("#settingsPage > div:nth-child(5) > h2").text("Zresetuj licznik");
$("#resetCountersForm > div > button").text("Zresetuj licznik");
$("#settingsPage > div:nth-child(6) > h2").text("Uruchom ponownie kontroler");
$("#restartControllerForm > div > button").text("Uruchom ponownie kontroler");
$("label[for='rule0value']").text("Zatrzymanie jazdy");
$("#in4").text("Obsługiwany jest tylko protokół HTTP, w przypadku serwerów lokalnych używany jest adres IP, a nie nazwa domeny.");
$("#in5").text("API wersja 1.X");
$("#in7").text("Aby to zaobserwować, rozpoznać nazwę użytkownika i języka v1 jako tokena w formacie");
$("#in7 > i").text("Login:Hasło");
$("#in8").text("Organizacja nie jest używana, po prostu ustawa słowa wartość organizacji.");
$("#in9").text("Adres URL jest taki sam jak w przypadku standardu v2.");
$("#influxForm > div > div:n-dziecko(1) > label").text("Włącz");
$("#mqttForm > div > button").text("Zapisz");
$("#influxForm > div > div:nth-child(2) > label").text("Częstotliwość rejestracji (sekundy)");
$("#influxForm > div > div:nth-child(3) > label").text("InfluxDB Write API URL");
$("#influxForm > div > div:nth-child(4) > label").text("token uwierzytelniania API");
$("#influxForm > div > div:nth-child(5) > label").text("Influx DB 2 Identyfikator organizacji");
$("#influxForm > div > div:nth-child(6) > label").text("Nazwa składki lub bazy danych");
$("#influxForm > div > przycisk").text("Zapisz");
$("#avrprogPage > div > ol > li:nth-child(1)").text("Włącz tryb programowania, aby zawiesić rejestrację karty SD i interfejs ekranu dotykowego TFT.");
$("#b11 > strong").text("Nie łącz");
$("#avrprogPage > div > p:nth-child(2)").text("Instrukcje:");
$("#avrprogPage > div > ol > li:nth-child(2)").text("Pobierz odpowiedni plik do programowania");
$("#avrprogPage > div > ol > li:nth-child(3)").text("Przeczytaj ostrzeżenie");
$("#avrprogPage > div > ol > li:nth-child(4)").text("Podłącz/podłącz urządzenie, które chcesz zaprogramować, do operatora ISP na kontrolerze");
$("#avrprogPage > div > ol > li:nth-child(5)").text("Wybierz oprogramowanie układowe.");
$("#avrprogPage > div > ol > li:nth-child(6)").text("Usuń urządzenie po znalezieniu");
$("#avrprogPage > div > ol > li:nth-child(7)").text("Zaprogramuj inne urządzenia według potrzeb");
$("#avrprogPage > div > ol > li:nth-child(8)").text("Wyłącz tryb programowania");
$("#AVRProgEnable").text("W zakresie oprogramowania układowego");
$("#AVRProgDisable").text("Wyłączony tryb lampy błyskowej");
$("#avrprogconfirm > ul > li:nth-child(1)").text("Przed programowaniem obsługi się, że odłączyłeś wszystkie kable zasilające i komunikacyjne od modułu/urządzenia.");
$("#avrprogconfirm > ul > li:nth-child(2)").text("Podłącz moduł do portu ISP na kontrolerze za pomocą kabla taśmowego lub adaptera, obsługuj się, że wycięcie jest dopasowane ze stykiem 1 na moduł." );
$("#avrprogconfirm > ul > li:nth-child(3)").text("Kliknij Firmware, aby rozpocząć programowanie");
$("#avrprogconfirm > ul > li:nth-child(4)").text(Odłącz kabel po wskazaniu programowania);
$("#ProgAVR").text("Oprogramowanie układowe");
$("#ProgAVRCanuluj").text("Anuluj");
$("#storagePage > h1").text("Pamięć");
$("#storagePage > div:n-dziecko(2) > h2").text("Karta SD");
$("#sdcardmissing").text("Karta SD nie jest zainstalowana/aktualnie dostępna");
$("#odmontuj").text("Wyłącz");
$("#mount").text("Połącz");
$("#savewifi").text("Zapisz Wi-Fi");
$("#saveconfig").text("Zapisz krótko");
$("#sdcardfiles > li:nth-child(1) > button").text("Przywróć");
$("#sdcardfiles > li:nth-child(2) > button").text("Przywróć");
$("#sdcardfiles > li:nth-child(3) > button").text("Przywróć");
$("#storagePage > div:n-dziecko(3) > h2").text("Flash");
$("#storagePage > div:n-dziecko(4) > h2").text("Logowanie");
$("#storagePage > div:nth-child(4) > p").text("Dane rzeczy i stany wyjściowe mogą działać jako pliki dziennika przy użyciu karty SD.");
$("#loggingForm > div > div:nth-child(1) > label").text("Logowanie na dołączone SD dołącz");
$("#loggingForm > div > div:nth-child(2) > label").text("Częstotliwość rejestracji danych rzeczy (sekundy)");
$("#loggingForm > div > button").text("Zapisz");
$("#v0").text("Integracja z Victron CANBUS");
$("#v1").text("Ta funkcja umożliwia DIY BMS dostarczanie danych i urządzeń BMS do urządzenia Victron GX przy korzystaniu z Victron CAN BMS.");
$("#v2").text("Nie wolno konfigurować oporników ograniczających na układach CAN L/H. W tym celu na sterowniku można wlutować zworkę JP1 zwartą.");
$("#v3").text("DIY BMS wyśle ​​alarmy do urządzenia Victron w oparciu o standardy dla systemu/wysokich napięć i temperatury.");
$("#v4").text("Dzięki temu urządzenie Victron może działać w celu uzyskania kontroli wydajności i współczynnika wydajności DVCC (opcjonalne).");
$("#victroncanbusPage > div:nth-child(2) > div:nth-child(5) > p").text("Te opcje mogą być kontrolowane:");
$("#victroncanbusPage > div:nth-child(2) > div:nth-child(5) > ul > li:nth-child(1)").text("Limit napięcia (VL): Maksymalne napięcie ładowania akceptowane obecnie przez akumulator.");
$("#victroncanbusPage > div:nth-child(2) > div:nth-child(5) > ul > li:nth-child(2)").text("Limit prądu ładowania (CCL): Maksymalny prąd ładowania zastosowany przez akumulator.");
$("#victroncanbusPage > div:nth-child(2) > div:nth-child(5) > ul > li:nth-child(3)").text("Limit prądu rozładowania (DCL): Maksymalny prąd rozładowania zastosowany przez akumulator.");
$("#victroncanbusPage > div:nth-child(2) > div:nth-child(6) > p").text("Niewłaściwe sterowanie tymi regulacjami może rozdzielić wzrok i skutki!");
$("#victroncanbusPage > div:nth-child(2) > div:nth-child(6) > p(1)").text("Integracja Victron jest obecnie w wersji EKSPERYMENTALNEJ, prosimy o dostarczenie problemów");
